
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: green502
    url: jdbc:mariadb://localhost:3306/not_todo

mybatis:
  type-aliases-package: com.green.nottodolist
  mapper-locations: mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html